# Generated by Django 5.1.4 on 2025-01-03 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonetique', '0002_texttransformation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttransformation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
